### ISSUE TITLE
Trigger Happy new face

### ISSUE THREAD

**Issue by foxmask** [push-things/django-th#150]
I'm testing a lot of things arround the UI, which is pretty basic today :)

So I made course on https://www.codecademy.com/ and after AngularJS, now its ReactJS :)

I try to find something, that I can understand quickly, to start to write something for TriggerHappy.

But whatever the choice I'll do to make a new UI, with such a "modern" Javascript project, I wont throw in the bin the actual work I did with the wizard.

At the end, my goal will be to propose a project that could be : 
- use with a *JS Front + [DRF](http://www.django-rest-framework.org/) as back
- use as it is today, simple and efficient, with every needed things for its work

**Comment by foxmask** [comment]
If someone is interested final choices are:

* [VueJS](https://vuejs.org/)
* [DjangoRestFramework](http://www.django-rest-framework.org/)

if you feel good with that, let's start :)

**Comment by georgduees** [comment]
Hi,
short question, hadn't a look at it right now. 
Is there already a REST-API in place, or does this needs to be written from the ground up?
So this would lead to two tasks:  Frontend| Backend...

Would be happy to help you with this!

**Comment by foxmask** [comment]
Actually DRF is used to handle 2 webhook from Taiga and Slack/Mattermost.

All have to be done :)
Then, yes two tasks to do.

I try all of this with a [notes taken app](https://github.com/orotangi/), but nodejs and webpack are not my friends :) I need to dive into webpack at least.

**Comment by foxmask** [comment]
Could be useful https://ariera.github.io/2017/09/26/django-webpack-vue-js-setting-up-a-new-project-that-s-easy-to-develop-and-deploy-part-1.html

**Comment by foxmask** [comment]
Won't be used , plan to rewrite everything with starlette
