### ISSUE TITLE
Request: Nextcloud and Owncloud Support

### ISSUE THREAD

**Issue by sunjam** [push-things/django-th#272]
## Feature Request 

Tell us which new functionality do you want included ?
    
[Nextcloud](http://nextcloud.com/) and [Owncloud](https://owncloud.com/) support, which allows users to self-host data (ala Dropbox and Drive) and run their own online services for email, calendars, contacts, maps, rss feeds, bookmarks, etc.
    
[Nextcloud Server](https://github.com/nextcloud/server) for files syncing and sharing.
[News Application for RSS & Atom Feeds](https://github.com/nextcloud/news)
[Mail Application for Email.](https://github.com/nextcloud/mail)
[Notes App for Evernote exports](https://github.com/nextcloud/notes)
[Bookmarks Application](https://github.com/nextcloud/bookmarks)
[Tasks Application with native iOS Reminders support](https://github.com/nextcloud/tasks)
[Calendar Application with CalDav support](https://github.com/nextcloud/calendar)
[Contacts Applications with CardDav support](https://github.com/nextcloud/contacts)
[Deck App for Trello and Kanban-style boards](https://github.com/nextcloud/deck)
and more....

**Comment by foxmask** [comment]
it's a list for Santa Claus :)

As I already told here and there, I do support others projects that I use myself.

Which is not the case at all here.

So If someone want to do it I could help and show the path to follow.

**Comment by poVoq** [comment]
Nextcloud uses a new web-standard called activitypub for many of it's federated services, see:
http://activitypub.rocks/
Maybe a generic support for that would be sufficient? Mastodon (since very recent) also uses that for server to server communication, so maybe the work is already half-way done?

**Comment by foxmask** [comment]
hi @poVoq , no, the work is not already half-way done :) 
ActivityPub is another way to "talk" to a new service, even if a python lib exists, a work has to be done :) 
And for me it's a very heavy job to setup nextcloud just for testing purpose.

I can help to show how to do the integration, but I wont do it because I wont use Nextcloud, like for another request about Facebook.

Anyway, Thank you for the info about activypub.

**Comment by foxmask** [comment]
If you want to contribute, feel free to reopen it
Otherwise I plan to rewrite everything with starlette.io
