### ISSUE TITLE
XMPP and indirect SMS/IoT support?

### ISSUE THREAD

**Issue by poVoq** [push-things/django-th#273]
## Feature Request

Would be nice if there was also an option to react to and send XMPP messages. There are already quite a few django related XMPP projects, so it should be probably easy to integrate. For example this:
https://github.com/alexmorozov/django-jabber
seems like it could easily push to XMPP?

You can also easily get a free XMPP account for testing purposes on a service like jix.im

There are also a lot of interesting further bridges for XMPP (see for example http://spectrum.im/ ). In addition you can quite easily link a XMPP account to a SMS sending service, and XMPP is also emerging as a IoT interoperability standard.

**Comment by poVoq** [comment]
Or maybe more general, this:
https://github.com/idlesign/django-sitemessage

**Comment by foxmask** [comment]
If you want to contribute, feel free to reopen it
Otherwise I plan to rewrite everything with starlette.io
