### ISSUE TITLE
Looking for Triggers by their description

### ISSUE THREAD

**Issue by foxmask** [push-things/django-th#275]
Implement a little search engine.

this will allow to lookup in the description of a service the expected data (for example)

**Comment by adriancarayol** [comment]
[Django-haystack](https://github.com/django-haystack/django-haystack) it can be useful.

**Comment by foxmask** [comment]
Hi @adriancarayol I used it [a long time ago](https://github.com/foxmask/django-th/search?utf8=%E2%9C%93&q=haystack&type=) but was not very satisfied.
I'll see if I wont find something else, but for a so simple thing, I think that a simple query on the [Service model](https://github.com/foxmask/django-th/blob/master/django_th/models/services.py#L12) should do the trick, at least until the project needs a more robust solution :)
