### ISSUE TITLE
Struggling with the docker support of this project.

### ISSUE THREAD

**Issue by Leopere** [push-things/django-th#300]
## Creating a new issue for a bug report

:bug: If you think you've spotted a bug, give as many details as possible by starting with that informations:

* docker build from source
* included dockerfile and included versions
* Details of the error/behavior:
I posted the details in the Gitter but basically the docker stuff needs a lot of work seemingly.  I can't go from a git clone, follow instructions, and get a running appliance.  

## Feature Request 

Just want to get a kick the tires instance up and running and Docker is usually the route but it seems this project may have abandoned the docker stuff.  Either that or the documentation has drifted significantly.

**Comment by foxmask** [comment]
I should try. but as nobody care about that project, I didn't take care of the docker file.

**Comment by Leopere** [comment]
Oh man I'll use the heck out of this project if it works!

The fact that you can run hooks based on RSS feeds alone is hugely useful for me.

**Comment by foxmask** [comment]
I followed this page https://trigger-happy.readthedocs.io/en/latest/docker_guide/index.html and all went well

after docker-compose up you can see 

```
web_1    | System check identified no issues (0 silenced).
web_1    | February 13, 2020 - 17:38:21
web_1    | Django version 2.2.10, using settings 'django_th.settings_docker'
web_1    | Starting development server at http://0.0.0.0:8000/
web_1    | Quit the server with CONTROL-C.
```

so follow the steps

* Build
* Database
* Run

You can meet problem but that could be because of some systemp lib not installed, like libtidy, or the redis server package not installed

**Comment by Leopere** [comment]
I will provide a asciinema recording to show my results shortly.

**Comment by Leopere** [comment]
It's also very strange that there is more than one FROM line in the default Dockerfile

**Comment by Leopere** [comment]
![image](https://user-images.githubusercontent.com/1068374/74461391-74196300-4e5c-11ea-8da7-8b4273329945.png)
Console recording of me following the steps directly as written only adding the undocumented assumed `git clone` at the beginning.
https://asciinema.org/a/7s4kmYu9SqmBkZr7Jp7alTg4X

**Comment by Leopere** [comment]
This here is the broken appliance that is deployed via following the instructions to the letter. http://s.nixc.us:8000/

**Comment by foxmask** [comment]
yes ; it's "normal" , As I've written this occurs because you did the step "Run" before the step "Database"
1) "Build"
* docker-compose build
2) "Database"
* docker-compose run web  python manage.py migrate --settings=django_th.settings_docker
* docker-compose run web  python manage.py loaddata initial_services --settings=django_th.settings_docker
* docker-compose run web  python manage.py createsuperuser --settings=django_th.settings_docker
3) "Run"
* docker-compose up

**Comment by Leopere** [comment]
Oh, I see! Can we possibly rewrite the instructions to reflect the better order?

**Comment by foxmask** [comment]
yes :)

**Comment by Leopere** [comment]
Okay still no joy 
https://asciinema.org/a/vFKWRztD4ofsFAQuXmS6oTm2m is my latest recording and I'll leave the site running on http://s.nixc.us:8000 for now so you can see.

**Comment by foxmask** [comment]
set the var 
```
ALLOWED_HOST = ['your.doamin.tld'] 
```
in the `settings_docker.py `

**Comment by Leopere** [comment]
Could it be set in the `docker-compose.yml` as an environment variable?

**Comment by foxmask** [comment]
i don't know I don't thing so.

**Comment by Leopere** [comment]
Okay so I'm struggling to locate `settings_docker.py` inside this repository is there a more precise path to see it in?

**Comment by foxmask** [comment]
you enter the path of that files 3 times :) it's in django_th folder 

django_th/settings_docker.py

**Comment by Leopere** [comment]
In here? 
![image](https://user-images.githubusercontent.com/1068374/74464381-6e724c00-4e61-11ea-81fe-a849c53ff825.png)

**Comment by foxmask** [comment]
nano django_th/settings_docker.py from where you are

**Comment by Leopere** [comment]
Ah I'm not sure why using the github search function wasn't showing me that file.

Okay, I'll add that is there any other commands that I should be re-running prior to re-launching?

**Comment by foxmask** [comment]
just the "up"

**Comment by Leopere** [comment]
```python
  File "/app/django_th/settings_docker.py", line 11
    'ALLOWED_HOSTS = ['s.nixc.us']',
                       ^
SyntaxError: invalid syntax
```

**Comment by foxmask** [comment]
```
from .th_settings import *

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',
        'USER': 'postgres',
        # 'PASSWORD': 'th_pass',
        'HOST': 'db',
        'PORT': 5432,
        
    }
}
ALLOWED_HOSTS = ['s.nixc.us']
```

**Comment by Leopere** [comment]
HA I guess I should learn to read Python that makes way more sense.

**Comment by Leopere** [comment]
Okay, awesome!  Is there a way that we can have that setting either documented or added to that install script that is run in the setup?

The thing is successfully running however sadly it doesn't auto redirect from http://my.tld:8000/ to http://my.tld:8000/th/ so you immediately get a 404 of a sort
![image](https://user-images.githubusercontent.com/1068374/74465338-34a24500-4e63-11ea-97ab-fc0478e1a60f.png)
However, as shown here
![image](https://user-images.githubusercontent.com/1068374/74465355-3c61e980-4e63-11ea-98c5-d20a2bcd3166.png)
it's up and running!

**Comment by foxmask** [comment]
yes yes 

now the login user is the superuser you created earlier

**Comment by Leopere** [comment]
Yes, that worked perfectly!

**Comment by Leopere** [comment]
#303 would be the continuation of this.
